/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"


void
sum_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	s  sumof_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUM_PROG, SUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
printf("\n ENTER N:");
        scanf("%d",&(sumof_1_arg.a));

	result_1 = sumof_1(&sumof_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	 else
    {
       printf("THE SUM IS %d\n",*result_1);
        }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sum_prog_1 (host);
exit (0);
}
